/**
 * "Help me understand" — general, non-personalised explanations of common
 * terms in IBD reports. These describe what a word generally means; they never
 * interpret the patient's own result. Content to be reviewed by a clinician
 * before production release (see /docs/COMPLIANCE.md).
 */
export const GLOSSARY: { match: RegExp; en: string; it: string }[] = [
  { match: /crp|c-reactive|reattiva|pcr/i,
    en: "C-reactive protein (CRP) is a blood marker that generally rises when there is inflammation somewhere in the body. It is not specific to the gut.",
    it: "La proteina C reattiva (PCR) è un marcatore nel sangue che in genere aumenta in presenza di infiammazione nel corpo. Non è specifica per l'intestino." },
  { match: /calprotectin/i,
    en: "Fecal calprotectin is a protein measured in a stool sample. In general it is used to monitor inflammation in the intestine.",
    it: "La calprotectina fecale è una proteina misurata in un campione di feci. In generale si usa per monitorare l'infiammazione intestinale." },
  { match: /h(a)?emoglobin|emoglobina|\bhb\b/i,
    en: "Hemoglobin is the protein in red blood cells that carries oxygen. It is commonly checked to look for anaemia.",
    it: "L'emoglobina è la proteina dei globuli rossi che trasporta l'ossigeno. Si controlla spesso per valutare l'anemia." },
  { match: /ferritin/i,
    en: "Ferritin reflects the body's iron stores. It can also rise during inflammation, so it is usually read together with other tests.",
    it: "La ferritina riflette le riserve di ferro. Può aumentare anche con l'infiammazione, quindi di solito si valuta insieme ad altri esami." },
  { match: /terminal ileum|ileo terminale|ileum|ileo/i,
    en: "The ileum is the last part of the small intestine; the terminal ileum is where it joins the large intestine.",
    it: "L'ileo è l'ultima parte dell'intestino tenue; l'ileo terminale è il punto in cui si unisce al colon." },
  { match: /aphthous|aftoid|afte/i,
    en: "Aphthous (or aphthoid) lesions are small, shallow sores of the gut lining seen during endoscopy.",
    it: "Le lesioni aftoidi sono piccole ulcerazioni superficiali della mucosa osservate durante l'endoscopia." },
  { match: /ulcer/i,
    en: "An ulcer is an area where the inner lining (mucosa) is broken. Reports often describe size, depth and location.",
    it: "Un'ulcera è un'area in cui il rivestimento interno (mucosa) è interrotto. I referti ne descrivono spesso dimensione, profondità e sede." },
  { match: /erythem|eritem/i,
    en: "Erythema means redness of the lining, which can be seen with irritation or inflammation.",
    it: "Eritema significa arrossamento della mucosa, che può comparire con irritazione o infiammazione." },
  { match: /mucosa/i,
    en: "The mucosa is the inner lining of the digestive tract.",
    it: "La mucosa è il rivestimento interno del tubo digerente." },
  { match: /stricture|stenos/i,
    en: "A stricture (stenosis) is a narrowing of part of the intestine.",
    it: "Una stenosi è un restringimento di un tratto dell'intestino." },
  { match: /fistul/i,
    en: "A fistula is an abnormal connection between two parts of the body, for example between the bowel and the skin.",
    it: "Una fistola è una comunicazione anomala tra due parti del corpo, per esempio tra intestino e cute." },
  { match: /granulom/i,
    en: "A granuloma is a small cluster of immune cells that a pathologist may see under the microscope.",
    it: "Un granuloma è un piccolo aggregato di cellule immunitarie che il patologo può osservare al microscopio." },
  { match: /crypt/i,
    en: "Crypts are tiny glands in the intestinal lining. Terms like 'cryptitis' or 'crypt abscess' describe changes a pathologist sees in them.",
    it: "Le cripte sono piccole ghiandole della mucosa intestinale. Termini come 'criptite' o 'ascesso criptico' descrivono alterazioni viste dal patologo." },
  { match: /biops/i,
    en: "A biopsy is a small tissue sample taken during a procedure and examined under a microscope (histology).",
    it: "Una biopsia è un piccolo campione di tessuto prelevato durante un esame e analizzato al microscopio (istologia)." },
  { match: /histolog|istolog/i,
    en: "Histology is the microscopic examination of tissue samples by a pathologist.",
    it: "L'istologia è l'esame al microscopio dei campioni di tessuto eseguito dal patologo." },
  { match: /ses-?cd/i,
    en: "SES-CD is a scoring system that endoscopists use to describe what they see in Crohn's disease. Only your care team can interpret your score.",
    it: "Il SES-CD è un punteggio usato dagli endoscopisti per descrivere quanto osservato nel Crohn. Solo il tuo team di cura può interpretare il tuo punteggio." },
  { match: /mayo/i,
    en: "The Mayo score is a scale doctors use to describe ulcerative colitis activity. Only your care team can interpret your score.",
    it: "Il punteggio Mayo è una scala usata dai medici per descrivere l'attività della colite ulcerosa. Solo il tuo team di cura può interpretarlo." },
  { match: /rutgeerts/i,
    en: "The Rutgeerts score describes what is seen at the join (anastomosis) after bowel surgery in Crohn's disease.",
    it: "Il punteggio di Rutgeerts descrive quanto osservato nella sede dell'anastomosi dopo un intervento intestinale nel Crohn." },
  { match: /anastomos/i,
    en: "An anastomosis is the surgical join between two ends of bowel.",
    it: "L'anastomosi è la giunzione chirurgica tra due estremità dell'intestino." },
  { match: /perianal|perianale/i,
    en: "Perianal means the area around the anus.",
    it: "Perianale indica la zona intorno all'ano." },
  { match: /pseudopolyp|pseudopolip/i,
    en: "Pseudopolyps are bumps in the lining that can form after past inflammation. They are not the same as true polyps.",
    it: "I pseudopolipi sono rilievi della mucosa che possono formarsi dopo un'infiammazione passata. Non sono veri polipi." },
];
